USE ROLE ANALYST_ROLE;
USE WAREHOUSE A4_WH;

SELECT * FROM FOURSQUARE_LOS_ANGELES.STANDARD.PLACES_US_LA_STANDARD_SCHEMA LIMIT 100;
SELECT * FROM FOURSQUARE_NEW_YORK.STANDARD.PLACES_US_NYC_STANDARD_SCHEMA LIMIT 100;
SELECT * FROM FOURSQUARE_OSAKA.STANDARD.PLACES_APAC_JP_OSAKA_STANDARD_SCHEMA LIMIT 100;
SELECT * FROM FOURSQUARE_MELBOURNE.STANDARD.PLACES_APAC_AU_Melbourne_STANDARD_SCHEMA LIMIT 100;